---
- hosts: all

  tasks:
    - name: Add PPA
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items:
        - '{{ ppa }}'
      become: yes

    - name: Install sublime text 3
      apt:
        name: sublime-text-installer
        update_cache: yes
        state: latest
      become: yes
      tags:
        - text

    - name: Add f.lux repo
      lineinfile:
        dest: '/etc/apt/sources.list.d/kilian-ubuntu-f_lux-wily.list'
        line: '{{ flux_repo }}'
        create: yes
      become: yes
      tags:
       - flux

    - name: Install f.lux key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: FAEB83059BD4ED25
        state: present
      become: yes
      tags:
        - flux

    - name: Install f.lux
      apt:
        name: fluxgui
        update_cache: yes
        state: latest
      become: yes
      tags:
        - flux

    - name: Add virtualbox repo
      lineinfile:
        dest: '/etc/apt/sources.list.d/virtualbox.list'
        line: '{{ virtualbox_repo }}'
        create: yes
      become: yes
      tags:
        - virtualbox

    - name: Add virtualbox key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present
      become: yes
      tags:
        - virtualbox

    - name: Install virtualbox
      apt:
        name: '{{ virtualbox_release_version }}'
        state: latest
        update_cache: yes
      become: yes
      tags:
        - virtualbox

    - name: Check if vagrant package is installed
      command: "dpkg-query --showformat='${Version}' --show vagrant"
      register: vagrant_check_install
      failed_when: vagrant_check_install.rc > 1
      changed_when: vagrant_check_install.rc == 1

    - name: Display checked vagrant version
      debug: msg={{ vagrant_check_install.stdout }}

    - name: Download vagrant deb package
      get_url:
        url: '{{ vagrant_deb_package_url }}'
        dest: '/tmp/vagrant.deb'
      when: vagrant_version not in vagrant_check_install.stdout
      tags:
        - vagrant

    - name: install vagrant
      apt:
        deb: '/tmp/vagrant.deb'
        state: present
      when: vagrant_version not in vagrant_check_install.stdout
      become: yes
      tags:
        - vagrant

    - name: Remove vagrant deb package
      file:
        path: '/tmp/vagrant.deb'
        state: absent
      when: vagrant_version not in vagrant_check_install.stdout
      tags:
        - vagrant

    - name: install common deb packages
      apt:
        name: '{{ item }}'
        state: present
      become: yes
      with_items:
        - '{{ common_deb_packages }}'
