---
- hosts: all

  tasks:
    - name: Install packages
      apt:
        name: '{{ item }}'
        state: latest
      become: yes
      with_items:
        - curl
        - python-apt
        - python-pycurl
        - python-dev
        - python-setuptools
        - shellcheck
      when: ansible_distribution == 'Ubuntu'
      tags:
        - always

    - name: Install pip
      easy_install:
        name: pip
        state: latest
      become: yes
      tags:
        - always

    - name: Install linters from pip
      pip:
        name: '{{ item }}'
        state: latest
      with_items:
        - pylint
        - ansible-lint
      become: yes
      tags:
        - always

    - name: Set no doc for gems
      lineinfile:
        dest: '/etc/gemrc'
        line: 'gem: --no-rdoc --no-ri'
        create: yes
      become: yes
      tags:
        - ruby

    - name: Install gems
      gem:
        name: '{{ item }}'
        state: latest
        user_install: no
      # become: yes # no for rbenv
      ignore_errors: yes
      with_items:
        - bundler
        - serverspec
        - haml-lint
        - ruby-lint
        - sqlint
        - rubocop
      tags:
        - ruby
