---
- hosts: all
  gather_facts: true

  tasks:
    - name: Install packages
      apt:
        name: '{{ item }}'
        state: latest
      with_items:
        - '{{ development_deb_packages }}'
      become: yes
      when: ansible_distribution == 'Ubuntu'
      tags:
        - always

    - block:
      - name: Install pip
        easy_install:
          name: pip
          state: latest

      - name: Install linters from pip
        pip:
          name: '{{ item }}'
          state: latest
        with_items:
          - '{{ pip_linters }}'
      become: yes
      tags: always

    - block:
      - name: Set no doc for gems
        lineinfile:
          dest: '/etc/gemrc'
          line: 'gem: --no-rdoc --no-ri'
          create: yes
        become: yes

      - name: Install gems
        gem:
          name: '{{ item }}'
          state: latest
          user_install: yes
        # become: yes # no for rbenv
        ignore_errors: yes
        with_items:
          - '{{ ruby_gems }}'
      tags: ruby

    - name: Set git configuration
      shell: "{{ item }}"
      with_items:
        - '{{ git_configs }}'
      tags: always

  roles:
    - { role: rbenv, tags: ruby, become: yes }
