---
- hosts: all

  tasks:

    - name: set branch name in PS1
      lineinfile:
        dest: '~/.bashrc'
        line: 'PS1="\[\e[0;32m\]\$(__git_ps1 "[%s]")\[\e[0m\]$PS1"'
        state: present
        create: yes
      tags: terminal
