---
- name: Add sublime text PPA
  apt_repository:
    repo: '{{ sublime_text_ppa }}'
    state: present
    update_cache: no
  become: yes

- name: Install sublime text 3
  apt:
    name: sublime-text-installer
    update_cache: yes
    state: latest
  become: yes

- name: Create sublime directory
  file:
    path: '{{ item }}'
    state: directory
    mode: 0755
  with_items:
    - ~/.config/sublime-text-3/Packages/User/
    - ~/.config/sublime-text-3/Installed Packages/

- name: Install PackageControl for Sublime
  get_url:
    url: https://packagecontrol.io/Package%20Control.sublime-package
    dest: ~/.config/sublime-text-3/Installed Packages/Package Control.sublime-package

- name: Copy sublime settings
  copy:
    src: Preferences.sublime-settings
    dest: ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
    force: no

- name: Install packages for Sublime
  git:
    repo: '{{ item.url }}'
    dest: '~/.config/sublime-text-3/Packages/{{ item.name }}'
  with_items:
    - '{{ sublime_packages_url_list }}'

- name: Check rubocop package installed
  stat:
    path: ~/.config/sublime-text-3/Packages/SublimeLinter-rubocop
  register: rubocop_package

- name: Check .rubocop.yml is provided
  stat:
    path: '{{ playbook_dir }}/files/.rubocop.yml'
  register: rubocopyml

- name: Copy .rubocop.yml
  copy:
    src: '.rubocop.yml'
    dest: ~/.rubocop.yml
  when: rubocop_package.stat.isdir and rubocopyml.stat.exists

- name: Check sublime-linter-rubocop settings is provided
  stat:
    path: '{{ playbook_dir }}/files/SublimeLinter.sublime-settings'
  register: rubocop_settings
  when: rubocop_package.stat.isdir

- name: Copy sublime-linter-rubocop settings
  copy:
    src: 'SublimeLinter.sublime-settings'
    dest: ~/.config/sublime-text-3/Packages/User/SublimeLinter.sublime-settings
    force: yes
  when: rubocop_package.stat.isdir and rubocop_settings.stat.exists

- name: Check SublimeGit package installed
  stat:
    path: ~/.config/sublime-text-3/Packages/SublimeGit
  register: sublimegit_package

- name: Check sublimegit settings is provided
  stat:
    path: '{{ playbook_dir }}/files/SublimeGit.sublime-settings'
  register: sublimegit_settings

- name: Copy sublimegit settings
  copy:
    src: 'SublimeGit.sublime-settings'
    dest: ~/.config/sublime-text-3/Packages/User/SublimeGit.sublime-settings
    force: yes
  when: sublimegit_package.stat.isdir and sublimegit_settings.stat.exists

- name: Check keybindings is provided
  stat:
    path: '{{ playbook_dir }}/files/Default (Linux).sublime-keymap'
  register: sublimegit_settings

- name: Copy keybindings
  copy:
    src: 'Default (Linux).sublime-keymap'
    dest: ~/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap
    force: yes
  when: sublimegit_package.stat.isdir and sublimegit_settings.stat.exists
